### ISSUE TITLE
Shrink VM

### ISSUE THREAD

**Issue by spinkham** [adi0x90/attifyos#4]
Shrunk your AppSec beta VM to under 4GB, which would let you forgo the ZIP mess and keep fat32.

Here's how:
#remove old kernels
`sudo apt purge linux-generic-lts-wily linux-headers-4.2.0-42 linux-headers-4.2.0-42-generic linux-headers-generic-lts-wily linux-image-4.2.0-42-generic linux-image-extra-4.2.0-42-generic linux-image-generic-lts-wily linux-headers-4.4.0-83 linux-headers-4.4.0-83-generic linux-image-4.4.0-83-generic linux-image-extra-4.4.0-83-generic
`
#cleanup apt package cache
`sudo apt-get clean`

#cleanup RVM
`sudo -i rvm cleanup all`

#empty filemanager trash
#(do this in the filemanager GUI)

Then, shutdown the VM and boot into a live CD. I use the xubuntu cd, use what you like

In the live CD, run the following:
 ` sudo apt-get install zerofree`
  `sudo zerofree /dev/sda1`

  #run checkdisk to make sure filesystem is OK
  `sudo fsck -f /dev/sda1`

  #clean up swap
  `sudo blkid /dev/sda5  #note UUID for later`
  `sudo swapoff -a && sudo dd if=/dev/zero of=/dev/sda5 bs=512`
  `sudo mkswap /dev/sda5 -U UUID-FROM_ABOVE_HERE`

Then shutdown the livecd session and export your VM however you normally do.  Between unnecessary files being cleaned up and the empty parts of the filesystem and swap being zeroed out, the ova exports about 1/2 the size.

**Comment by adi0x90** [comment]
Thanks a lot Steve! Really helpful. 
Will use this in the next release of AttifyOS.
